# Generated by Django 4.1.6 on 2023-02-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrameworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя фреймворка')),
                ('language', models.CharField(max_length=50, verbose_name='Язык фреймворка')),
            ],
            options={
                'verbose_name': 'Фреймворк',
                'verbose_name_plural': 'Фреймворки',
            },
        ),
        migrations.AddIndex(
            model_name='frameworkmodel',
            index=models.Index(fields=['language'], name='framework_f_languag_451cdb_idx'),
        ),
    ]
