# Generated by Django 4.1.6 on 2023-02-04 17:24

from django.db import migrations, transaction


def field_db(apps, schema_editor):
    Framework = apps.get_model('framework', 'FrameworkModel')

    with transaction.atomic():
        Framework.objects.create(name="React", language="Javascript")
        Framework.objects.create(name="Vue", language="Javascript")
        Framework.objects.create(name="FastApi", language="Python")
        Framework.objects.create(name="Laravel", language="PHP")
        Framework.objects.create(name="Spring", language="Java")


class Migration(migrations.Migration):
    dependencies = [
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(field_db)
    ]
